(cl:in-package watrix_vp-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPSWEEK-VAL
          GPSWEEK
          GPSTIME-VAL
          GPSTIME
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          VELOCITY_EARTH-VAL
          VELOCITY_EARTH
          VELOCITY_NORTH-VAL
          VELOCITY_NORTH
          VELOCITY_UP-VAL
          VELOCITY_UP
          BASELINE-VAL
          BASELINE
          NSV1-VAL
          NSV1
          NSV2-VAL
          NSV2
          STATUS-VAL
          STATUS
          POSITION_COVARIANCE-VAL
          POSITION_COVARIANCE
          ANGULAR_COVARIANCE-VAL
          ANGULAR_COVARIANCE
          POSITION_COVARIANCE_TYPE-VAL
          POSITION_COVARIANCE_TYPE
          ANGULAR_COVARIANCE_TYPE-VAL
          ANGULAR_COVARIANCE_TYPE
))