// Generated by gencpp from file hdl_graph_slam/DumpGraphRequest.msg
// DO NOT EDIT!


#ifndef HDL_GRAPH_SLAM_MESSAGE_DUMPGRAPHREQUEST_H
#define HDL_GRAPH_SLAM_MESSAGE_DUMPGRAPHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdl_graph_slam
{
template <class ContainerAllocator>
struct DumpGraphRequest_
{
  typedef DumpGraphRequest_<ContainerAllocator> Type;

  DumpGraphRequest_()
    : destination()  {
    }
  DumpGraphRequest_(const ContainerAllocator& _alloc)
    : destination(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DumpGraphRequest_

typedef ::hdl_graph_slam::DumpGraphRequest_<std::allocator<void> > DumpGraphRequest;

typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest > DumpGraphRequestPtr;
typedef boost::shared_ptr< ::hdl_graph_slam::DumpGraphRequest const> DumpGraphRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdl_graph_slam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hdl_graph_slam': ['/home/shiyang/advanced_car/src/hdl_graph_slam/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e47796db9d7d90bff30cd181ffc714b";
  }

  static const char* value(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e47796db9d7d90bULL;
  static const uint64_t static_value2 = 0xff30cd181ffc714bULL;
};

template<class ContainerAllocator>
struct DataType< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdl_graph_slam/DumpGraphRequest";
  }

  static const char* value(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string destination\n\
";
  }

  static const char* value(const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DumpGraphRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdl_graph_slam::DumpGraphRequest_<ContainerAllocator>& v)
  {
    s << indent << "destination: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDL_GRAPH_SLAM_MESSAGE_DUMPGRAPHREQUEST_H
